bee_cycles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_cart, name='view_cart'),
    path('add/<item_id>', views.add_to_cart, name='add_to_cart'),
    path('adjust/<item_id>/', views.adjust_cart, name='adjust_cart'),
    path('remove/<item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name="products"),
    path('<int:product_id>/', views.product_details, name="product_details"),
    path('add/', views.add_product, name="add_product"),
    path('edit/<int:product_id>/', views.edit_product, name="edit_product"),
    path('delete/<int:product_id>/', views.delete_product,
         name="delete_product"),
]

checkout/models.py
from django.db import models
import uuid

from django.db.models import Sum

from django_countries.fields import CountryField
from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    order_number = models.CharField(max_length=32, null=False, editable=False)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    city = models.CharField(max_length=40, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, default=0)
    original_cart = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(max_length=254, null=False,
                                  blank=False, default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        self.order_total = self.lineitems.aggregate(Sum('lineitem_total'))['lineitem_total__sum'] or 0
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    order = models.ForeignKey(Order, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='lineitems')
    product = models.ForeignKey(Product, null=False, blank=False,
                                on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True,
                                    blank=True)  # XS, S, M, L, XL
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(max_digits=6, decimal_places=2,
                                         null=False, blank=False,
                                         editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(max_digits=6, decimal_places=2,
                                 null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name

products/forms.py
from django import forms
from .widgets import CustomClearableFileInput
from .models import Product, Category


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    image = forms.ImageField(label='Image', required=False,
                             widget=CustomClearableFileInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]

        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-black'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from .models import Product, Category
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower

from .forms import ProductForm


# Create your views here.

def all_products(request):
    """ A view to show all products, including sorting and search queries """

    products = Product.objects.all()
    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = get_object_or_404(Category, name__in=categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'current_categories': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_details(request, product_id):
    """ A view to show individual product details """

    product = get_object_or_404(Product, pk=product_id)

    context = {
        'product': product,
    }

    return render(request, 'products/product_details.html', context)


@login_required
def add_product(request):
    """ Add a product to the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product!')
            return redirect(reverse('product_details', args=[product.id]))
        else:
            messages.error(request, 'Failed to add product. Please ensure the form is valid.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, product_id):
    """ Edit a product in the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Successfully updated product!')
            return redirect(reverse('product_details', args=[product.id]))
        else:
            messages.error(request, 'Failed to update product. Please ensure the form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """ Delete a product from the store """
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product deleted!')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %} 
{% load static %} 
{% block page_header %}
<!--Push content down-->
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %} 
{% block content %}
<div class="overlay"></div>
<div class="container mt-lg-3">
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8 text-center">
            <hr />
            <h2 class="mb-4 text-uppercase font-weight-bold">Product Management</h2>
            <h5>Add a Product</h5>
            <hr />
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8">
            <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %} 
                {% for field in form %} 
                    {% if field.name != 'image' %} 
                        {{ field | as_crispy_field }} 
                    {% else %} 
                        {{ field }} 
                    {% endif %} 
                {% endfor %}
                <div class="text-right">
                    <a class="btn bg-warning border-dark font-weight-bold" href="{% url 'products' %}">Cancel</a>
                    <button class="btn bg-warning border-dark font-weight-bold" type="submit">Add Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %} 
{% block postloadjs %} 
{{ block.super }}
<script>
    $("#new-image").change(function () {
        let file = $("#new-image")[0].files[0];
        $("#filename").text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %} 
{% load static %} 
{% block page_header %}
<!--Push content down-->
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %} 
{% block content %}
<div class="overlay"></div>
<div class="container mt-lg-3">
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8 text-center">
            <hr />
            <h2 class="text-uppercase font-weight-bold mb-4">Product Management</h2>
            <h5>Edit a Product</h5>
            <hr />
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8">
            <form method="POST" action="{% url 'edit_product' product.id %}" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %} 
                {% for field in form %} 
                    {% if field.name != 'image' %} 
                        {{ field | as_crispy_field }} 
                    {% else %} 
                        {{ field }} 
                    {% endif %} 
                {% endfor %}
                <div class="text-right">
                    <a class="btn bg-warning border-dark font-weight-bold" href="{% url 'products' %}">Cancel</a>
                    <button class="btn bg-warning border-dark font-weight-bold" type="submit">Update Product</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %} 
{% block postloadjs %} 
{{ block.super }}
<script>
    $("#new-image").change(function () {
        let file = $("#new-image")[0].files[0];
        $("#filename").text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/product_details.html
{% extends "base.html" %} 
{% load static %} 
{% block page_header %}
<!--Push content down-->
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %} 
{% block content %}
<div class="container footer-down">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            {% if product.image %}
                <img src="{{ product.image.url }}" class="card-img-top img-fluid" alt="{{ product.name }}" />
            {% else %}
                <img src="{{ MEDIA_URL }}no-image-available.jpg" class="card-img-top img-fluid" alt="{{ product.name }}" />
            {% endif %}
        </div>
        <div class="col-sm-12 col-md-6">
            <h5 class="card-title mt-5">{{ product.name }}</h5>
            {% if product.price %}
            <div class="mt-3">
                <p class="lead mb-0 font-weight-bold">€{{ product.price }}</p>
            </div>
            {% endif %} 
            {% if product.category %}
            <div class="mt-1">
                <i class="fas fa-tags"> {{ product.category.friendly_name }}</i>
            </div>
            {% endif %} 
            {% if product.rating %}
            <div class="mt-1">
                <i class="fas fa-star"> {{ product.rating }}/5</i>
            </div>
            {% else %}
            <small>No Rating</small>
            {% endif %} 
            {% if request.user.is_superuser %}
            <small>
                <a href="{% url 'edit_product' product.id %}"><i class="fas fa-edit"></i> Edit</a> |
                <a class="text-danger" href="{% url 'delete_product' product.id %}"><i class="fas fa-times-circle"></i> Delete</a>
            </small>
            {% endif %}
            <div class="product-description mt-3">
                <span>{{ product.description }}</span>
            </div>
            <form class="form" action="{% url 'add_to_cart' product.id %}" method="POST">
                {% csrf_token %}
                <div class="form-row">
                    {% if product.has_sizes %}
                    <div class="col-12">
                        <p><strong>Size:</strong></p>
                        <select class="form-control rounded-0 w-50" name="product_size" id="id_product_size">
                            <option value="xs">XS</option>
                            <option value="s">S</option>
                            <option value="m" selected>M</option>
                            <option value="l">L</option>
                            <option value="xl">XL</option>
                        </select>
                    </div>
                    {% endif %}
                    <div class="col-12">
                        <p class="mt-3"><strong>Quantity:</strong></p>
                        <div class="form-group w-50">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <button class="decrement-qty btn" data-item_id="{{ product.id }}" id="decrement-qty_{{ product.id }}">
                                        <span class="icon">
                                            <i class="fas fa-minus"></i>
                                        </span>
                                    </button>
                                </div>
                                <input class="form-control qty_input" type="number" name="quantity" value="1" min="1" max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}" />
                                <div class="input-group-append">
                                    <button class="increment-qty btn" data-item_id="{{ product.id }}" id="increment-qty_{{ product.id }}">
                                        <span class="icon">
                                            <i class="fas fa-plus"></i>
                                        </span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-12">
                        <a href="{% url 'products' %}" class="btn text-uppercase border border-dark bg-warning mt-0 mt-md-5 mb-3 mr-2 font-weight-bold keep-shopping-btn">
                            <span class="icon">
                                <i class="fas fa-chevron-left"></i>
                            </span>
                            Keep Shopping
                        </a>
                        <input type="submit" class="btn text-uppercase mt-0 mt-md-5 mb-3 border border-dark bg-warning font-weight-bold add-to-cart-btn" value="Add to Cart" />
                    </div>
                    <input type="hidden" name="redirect_url" value="{{ request.path }}" />
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %} 
{% block postloadjs %} 
{{ block.super }} 
{% include 'products/includes/quantity_script.html' %} 
{% endblock %}

products/templates/products/products.html
{% extends "base.html" %} 
{% load static %} 
{% block page_header %}
<!--Push content down-->
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}
{% block content %}
    <div class="container-fluid">
    <div class="row justify-content-center">
            <h2 class="text-uppercase font-weight-bold mt-4">Products</h2>
        </div>
        <div class="row">
            <div class="col-12 d-none d-lg-block text-center mt-3">
                <span>
                    <a href="{% url 'products' %}" class="btn btn-sm btn-outline-dark">All</a>
                    <a href="{% url 'products' %}?category=city_bikes" class="btn btn-sm btn-outline-dark">City Bikes</a>
                    <a href="{% url 'products' %}?category=electric_bikes" class="btn btn-sm btn-outline-dark">Electric Bikes</a>
                    <a href="{% url 'products' %}?category=road_bikes" class="btn btn-sm btn-outline-dark">Road Bikes</a>
                    <a href="{% url 'products' %}?category=helmets" class="btn btn-sm btn-outline-dark">Helmets</a>
                    <a href="{% url 'products' %}?category=lights" class="btn btn-sm btn-outline-dark">Lights</a>
                    <a href="{% url 'products' %}?category=locks" class="btn btn-sm btn-outline-dark">Locks</a>
                    <a href="{% url 'products' %}?category=sunglasses" class="btn btn-sm btn-outline-dark">Sunglasses</a>
                    <a href="{% url 'products' %}?category=new_arrivals" class="btn btn-sm btn-outline-dark">New Arrivals</a>
                    <a href="{% url 'products' %}?category=deals" class="btn btn-sm btn-outline-dark">Deals</a>
                    <a href="{% url 'products' %}?category=clearance" class="btn btn-sm btn-outline-dark">Clearance</a>
                </span>
            </div>
            <div class="col-12 mt-3 d-lg-none">
                    <div class="input-group mb-3">
                    <div class="input-group d-flex justify-content-center">
                            <button class="btn btn-outline-dark dropdown-toggle btn-lg" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% if current_categories %}{{ current_categories.friendly_name }}{% else %}All{% endif %}</button>
                        <div class="dropdown-menu">
                            <a href="{% url 'products' %}" class="dropdown-item">All</a>
                            <a href="{% url 'products' %}?category=city_bikes" class="dropdown-item">City Bikes</a>
                            <a href="{% url 'products' %}?category=electric_bikes" class="dropdown-item">Electric Bikes</a>
                            <a href="{% url 'products' %}?category=road_bikes" class="dropdown-item">Road Bikes</a>
                            <a href="{% url 'products' %}?category=helmets" class="dropdown-item">Helmets</a>
                            <a href="{% url 'products' %}?category=lights" class="dropdown-item">Lights</a>
                            <a href="{% url 'products' %}?category=locks" class="dropdown-item">Locks</a>
                            <a href="{% url 'products' %}?category=sunglasses" class="dropdown-item">Sunglasses</a>
                            <a href="{% url 'products' %}?category=new_arrivals" class="dropdown-item">New Arrivals</a>
                            <a href="{% url 'products' %}?category=deals" class="dropdown-item">Deals</a>
                            <a href="{% url 'products' %}?category=clearance" class="dropdown-item">Clearance</a>
                        </div>
                    </div>
                    </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="row mt-1 mb-2">
                    <div class="col-12 col-md-6 my-auto order-md-last d-flex justify-content-center justify-content-md-end">
                        <div class="sort-select-wrapper w-50">
                            <select id="sort-selector" class="custom-select custom-select-sm border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
                                <option value="reset" {% if current_sorting == 'None_None' %}selected{% endif %}>Sort by...</option>
                                <option value="price_asc" {% if current_sorting == 'price_asc' %}selected{% endif %}>Price (low to high)</option>
                                <option value="price_desc" {% if current_sorting == 'price_desc' %}selected{% endif %}>Price (high to low)</option>
                                <option value="rating_asc" {% if current_sorting == 'rating_asc' %}selected{% endif %}>Rating (low to high)</option>
                                <option value="rating_desc" {% if current_sorting == 'rating_desc' %}selected{% endif %}>Rating (high to low)</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 order-md-first">
                        <p class="mt-3 text-md-left">
                            {{ products|length }} Products{% if search_term %} found for <strong>"{{ search_term }}"</strong>{% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-sm-center">
            {% for product in products %}
            <div class="col-sm-6 col-md-4 col-lg-3 text-center mb-5">
                <div class="card h-100">
                    <a href="{% url 'product_details' product.id %}">
                    {% if product.image %}
                        <img src="{{ product.image.url }}" class="card-img-top img-fluid" alt="{{ product.name }}">
                    {% else %}
                        <img src="{{ MEDIA_URL }}no-image-available.jpg" class="card-img-top img-fluid" alt="{{ product.name }}">
                    {% endif %}
                    </a>
                    <div class="card-body bg-warning">
                        <h5 class="card-title">{{ product.name }}</h5>
                        {% if product.price %}
                            <div>
                                <p class="lead mb-0 font-weight-bold">€ {{ product.price }}</p>
                            </div>
                        {% endif %}
                        {% if product.category %}
                        <div>
                            <i class="fas fa-tags"> {{ product.category.friendly_name }}</i>
                        </div>
                        {% endif %}
                        {% if product.rating %}
                        <div>
                            <i class="fas fa-star"> {{ product.rating }}/5</i>
                        </div>
                        {% endif %}
                        {% if request.user.is_superuser %}
                            <small class="ml-3">
                                <a href="{% url 'edit_product' product.id %}"><i class="fas fa-edit"></i> Edit</a> | 
                                <a class="text-danger" href="{% url 'delete_product' product.id %}"><i class="fas fa-times-circle"></i> Delete</a>
                            </small>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="btt-button shadow-sm border border-black bg-dark">
        <a class="button-up d-flex h-100 text-decoration-none">
            <i class="fas fa-arrow-up text-warning mx-auto my-auto"></i>
        </a>	
    </div>
{% endblock %}
{% block postloadjs %}
    {{ block.super }}
    <script>
		$('.button-up').click(function(e) {
			window.scrollTo(0,0)
		})
	</script>
    
    <script>
        $('#sort-selector').change(function() {
            let selector = $(this);
            let currentUrl = new URL(window.location);

            let selectedValue = selector.val();
            if(selectedValue != "reset"){
                let sort = selectedValue.split("_")[0];
                let direction = selectedValue.split("_")[1];

                currentUrl.searchParams.set("sort", sort);
                currentUrl.searchParams.set("direction", direction);

                window.location.replace(currentUrl);
            } else {
                currentUrl.searchParams.delete("sort");
                currentUrl.searchParams.delete("direction");

                window.location.replace(currentUrl);
            }
        })
        // added active btn btn-sm btn-outline-dark classes as per https://www.youtube.com/watch?v=BI3kNsTruWo
        let currentLocation = location.href;
        let menuItem = document.querySelectorAll('span a');
        let menuLength = menuItem.length;
        let dropdownItem = document.getElementsByClassName('dropdown-item');
        for(let i = 0; i<menuLength; i++){
            if(menuItem[i].href === currentLocation){
                menuItem[i].className = 'active btn btn-sm btn-outline-dark';
            }
        }
        for(let i = 0; i<dropdownItem.length; i++){
            if(dropdownItem[i].href === currentLocation){
                dropdownItem[i].className = 'active dropdown-item bg-dark';
            }
        }

    </script>
{% endblock %}